### ISSUE TITLE
Constraint bottom/top of Walls to Levels

### ISSUE THREAD

**Issue by theoryshaw** [buildingSMART/IFC4-CV#12]
Perhaps more appropriate for [Design Handover View](https://github.com/BuildingSMART/IFC4-CV/#ifc4-design-handover-view), but is it possible to support the exchange of walls that are 'constrained' or 'linked' to building level elevations?

**Comment by timchipman** [comment]
For IfcWallStandardCase, there could be an implicit agreement where the base is anchored to a slab (IfcSlab with IfcRelConnectsElements, falling back on relative placement to IfcBuildingStorey) and the top is clipped by the greater of IfcMaterialLayerSetUsage.ReferenceExtent (if provided) or elements that clip the top of the wall (simple case being another slab, more complex cases being vaulted roofs, beams, ...).

The future Parametric View could support something more generic, where IfcRelAssociatesConstraint+IfcMetric+IfcAppliedValue+IfcReference may be used to construct explicit formulas.

**Comment by timchipman** [comment]
To constrain a wall to surrounding elements, use IfcRelConnectsElements between the IfcWall and the IfcSlab underneath and above, and use IfcRelConnectsPathElements for any adjoining IfcWall's. Whether an importing application observes such behavior is probably not something we can standardize however.
