### ISSUE TITLE
Calendars for occupancy in Design Transfer View

### ISSUE THREAD

**Issue by timchipman** [buildingSMART/IFC4-CV#17]
There have been multiple requests for capturing calendars on spaces or elements to indicate recurring calendars of occupancy or equipment usage. IFC4 introduced the entity IfcWorkCalendar which can capture recurring time intervals and supports all calendar scheduling capabilities found in Outlook and Microsoft Project. The main intention of the data type is for scheduling tasks, however it is generic to support any other recurring calendar scenario such as occupancy.

We initially assumed this was out of scope, as none of the major design platforms would appear to collect this information, and the intent is to coordinate the results of a design, not the design intent or any comprehensive set of parameters for achieving the resulting design. Though as this issue keeps coming up, perhaps it makes sense to get wider input from the group. While we're at the 11th hour before uploading the release candidate, if we get sufficient feedback that is representative of implementers, we could act on it.

So some questions for software vendors who will be exporting Design Transfer View:
1. Do you collect calendar information about spaces or other objects?
2. Would you be able to export it according to the IfcWorkCalendar data type?

**Comment by MarieHermanova** [comment]
Scia Engineer allows to define construction stages for some objects. The object knows in which stage was created and when removed but there is no date or time. It means we could not use IfcWorkCalendar for exporting Design Transfer View.

**Comment by AngelVelezSosa** [comment]
I've surveyed several of the Autodesk products that support IFC, and their support is similar to Scia's above.  Navisworks has more support but does not yet export IFC (it just imports).  So I would say that we could not collect the information for export.

**Comment by NickNisbet** [comment]
UK’s Synchro 4d/5d application uses both the product and process models fully in its exports. 

Regards,

Nick.

AEC3 will be delivering the BSI Masterclass http://pages.bsigroup.com/webmail/35972/147475106/a1226a2f69c90945d2d1bfa82ae73976  30 March – 1 April 2015, London, BSI Chiswick

on BS1192 Part 4 on the UK use of COBie, along side David Churcher on AIM (PAS1192 part 3) and  Paul Shillcock on PIM (PAS1192 part 2) .  

AEC3 is pleased to announce that  Lloyds Register awards BIM accreditation to AEC3 http://www.lloydsregister.co.uk/news-and-events/news/249879-lloyds-register-awards-bim-accreditation-to-aec3.aspx 

Nicholas Nisbet MA(Cantab) DipArch(UNL)   

Director:                            AEC3 UK Ltd 

Web:                                   http://www.aec3.com http://www.aec3.com/ 

E-mail:                                nn@aec3.com

Direct:                                +44 (0) 1494 714 933    

Mobile:                              +44 (0) 781 616 8554               

Skype:                                nicholasnisbet 

AEC3Logo-Pantone7462C-432C

Registered Address:       46 St Margaret's Grove, Great Kingshill, High Wycombe, Bucks, HP15 6HP, UK

Registered in the UK:     03484881

Visiting Professor:            University of Cardiff, School of Engineering

Technical Coordinator:  buildingSMART UK Chapter

ifcXML Coordinator:       buildingSMART Model Support Group

Web:                                   http://www.buildingsmart.org.uk/

E-mail:                                nn@buildingSMART.org.uk 

BuildingSmart-UK&I-Member-2015_450x113

*********\* Confidentiality Notice **********.

This e-mail and any file(s) transmitted with it, is intended for the exclusive use by the person(s) mentioned above as recipient(s). This e-mail may contain confidential information and/or information protected by intellectual property rights or other rights. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution, copying, or action taken in relation to the contents of and attachments to this e-mail is strictly prohibited and may be unlawful. If you have received this e-mail in error, please notify the sender and delete the original and any copies of this e-mail and any printouts immediately from your system and destroy all copies of it.

**Comment by timchipman** [comment]
Thanks for the great feedback, much appreciated. Our guidance is clear, IfcWorkCalendar will remain out of scope.
