### ISSUE TITLE
IFCMaterial to have a GUID associated with it

### ISSUE THREAD

**Issue by theoryshaw** [buildingSMART/IFC4-CV#18]
For IFC5, would it be possible for an IFCMaterial to have a GUID associated with it?

Didn't know where to place this question, since there was an IFC5 repo out there.

Please let me know if there's a better location for this request. 

Thanks Much, Ryan

**Comment by TLiebich** [comment]
Hi Ryan,

please log such issues at http://jira.buildingsmart.org/browse/IFR (just 
opened it up to go beyond IFC4),


beste Grüße / kind regards
Thomas

--

Dr.-Ing. Thomas Liebich
Geschäftsführer / Director

------------------------------------------------------------------------

AEC3 Deutschland GmbH
AG München, Handelsregister HRB 164221
Geschäftsführer: Dr. Thomas Liebich, Kerstin Hausknecht

	

Joseph-Wild-Str. 13, D-81829 München
Tel: +49-89-18703223
Mob: +49-171-2628789

	

E-Mail: tl@aec3.de <mailto:tl@aec3.de>
Internet: www.aec3.de <http://www.aec3.de>
Fax: +49-89-18703224

Der Inhalt dieser E-Mail (einschließlich etwaiger beigefügter Dateien) 
ist vertraulich und nur für den Empfänger bestimmt. Sollten Sie nicht 
der bestimmungsgemäße Empfänger sein, ist Ihnen jegliche Offenlegung, 
Vervielfältigung, Weitergabe oder Nutzung des Inhalts untersagt. Bitte 
informieren Sie in diesem Fall unverzüglich den Absender und löschen Sie 
die E-Mail (einschließlich etwaiger Anhänge) von Ihrem System. | /This 
email and any attachments are confidential to the intended recipient and 
may also be privileged. If you are not the intended recipient please 
delete it from your system and notify the sender. You should not copy it 
or use it for any purpose nor disclose or distribute its contents to any 
other person./

------------------------------------------------------------------------
Am 30.12.2016 um 20:32 schrieb Ryan Schultz:

**Comment by theoryshaw** [comment]
Thanks @TLiebich 

Will do!
