### ISSUE TITLE
Handling type information for IFC4 Reference View

### ISSUE THREAD

**Issue by TLiebich** [buildingSMART/IFC4-CV#2]
When defining the exact scope of the IFC4 Reference View - how to handle types, and what kind of information 
- geometry
- properties
- material

shall be handled by the type and could be overridden at the occurrence level.

**Comment by theoryshaw** [comment]
related pingback [conversation](https://github.com/BuildingSMART/mvdXML/issues/3)

**Comment by timchipman** [comment]
For geometry, see the other issue on tessellation.
For properties, seems single values, enumerated values, and perhaps bounded values should be in scope; the other ones are much more obscure -- if materials are in scope along with related property sets, some of those material property sets rely on complex properties (perhaps they should be changed to not require complex properties)
For material, several things to consider: is the reference view intended to be used for structural analysis or energy analysis? If yes, then include; if not, then don't. Style information for materials can be defined at geometry instead.

**Comment by TLiebich** [comment]
so we will include:
- type based material definitions with overriding at occurrence
- type based property sets with overriding at occurrence
- type based geometry (representation maps) with mapped items at occurrence
