### ISSUE TITLE
IFC CV Requirements

### ISSUE THREAD

**Issue by LassiLiflander** [buildingSMART/IFC4-CV#7]

**Comment by LassiLiflander** [comment]
It shall be possible to represent all typical geometrical members using swept solid presentation. This includes straight, curved and tapered members, as well as members with multiple corner points (polybeams). [Probably IfcSectionedSpine could be the solution.]

**Comment by timchipman** [comment]
For DHV in general, and for the RV where "members" means beams and columns, that seems achievable. 

Though in the RV, anything with voids (walls, slabs, etc.) would need face-based models as CSG is out of scope.

**Comment by timchipman** [comment]
SolidModel Geometry is in scope is as follows:

  IfcSolidModel R   D
      IfcCsgSolid       D
      IfcManifoldSolidBrep      D
        IfcAdvancedBrep     D
          IfcAdvancedBrepWithVoids  
        IfcFacetedBrep      D
          IfcFacetedBrepWithVoids  
      IfcSweptAreaSolid R   D
        IfcExtrudedAreaSolid    R   D
          IfcExtrudedAreaSolidTapered       D
        IfcFixedReferenceSweptAreaSolid     D
        IfcRevolvedAreaSolid    R   D
          IfcRevolvedAreaSolidTapered       D
        IfcSurfaceCurveSweptAreaSolid       D
      IfcSweptDiskSolid R   D
        IfcSweptDiskSolidPolygonal      

(R = Reference View, D = Design Transfer View)
