### ISSUE TITLE
Support for '2D plan elements'

### ISSUE THREAD

**Issue by theoryshaw** [buildingSMART/IFC4-CV#8]
It appears via the [FM Basic Handover](http://www.buildingsmart-tech.org/specifications/ifc-view-definition/fm-handover-aquarium/fm-basic-handover/fm-basic-handover) MVD that the following '2D plan elements' are supported.  

[IfcAnnotationFillArea](http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcpresentationdefinitionresource/lexical/ifcannotationfillarea.htm) (generically called, a 'filled region', or 'hatch)
[IfcTextLiteralWithExtent](http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcpresentationdefinitionresource/lexical/ifctextliteralwithextent.htm) (generically called, a 'text annotation')

Would it be possible to get support for these in IFC4-CV, as well?

**Comment by timchipman** [comment]
Probably makes sense to include IfcAnnotation along with its various representation items such as the entities mentioned above for the Design Handover View; probably not for the Reference View though (it imposes additional special cases that implementations would need to handle, particularly for all the text style configurations when rendering text).  Such annotations can be rendered in 2D or 3D.

**Comment by theoryshaw** [comment]
Would agree to include them in DHV.
